### test insert local
POST {{localUrl}}message/create.php
Content-Type: application/json

{
  "name" : "gatto",
  "email" : "gatto",
  "subject" : "gatto",
  "message" : "gatto"
}

### test insert prod
POST {{prodUrl}}message/create.php
Content-Type: application/json

{
  "name" : "name",
  "email" : "email",
  "subject" : "subject",
  "message" : "message"
}
