### test insert
POST {{localUrl}}message/create.php
Content-Type: application/json

{
  "name" : "gatto",
  "email" : "gatto",
  "subject" : "gatto",
  "message" : "gatto"
}

### test insert
POST {{prodUrl}}message/create.php
Content-Type: application/json

{
  "name" : "gatto",
  "email" : "gatto",
  "subject" : "gatto",
  "message" : "gatto"
}