on:
  push:
    branches: [ develop__ ]
name: 🚀 Deploy website on push
jobs:
  build:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          exclude: '[**/.git*, **/.git*/**, **/node_modules/**, deploy_localhost.*, LICENSE, README.md, **/docs/**, test/**, **/sql_scripts/**, fe/**, src/**, public/**, package.json, package-lock.json, tsconfig.json]'

